version: "3"

services:
  mysql:
    container_name: "${PROJECT_NAME}_mysql"
    image: mysql:8.0
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ~/mysql-data/itron/store:/var/lib/mysql
    ports:
      - "3066:3306"
    networks:
      - store

  php:
    build:
      context: dev-local/php-fpm
      args:
        PHP_VER: $PHP_VERSION
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      PHP_IDE_CONFIG: $XDEBUG_IDE_CONFIG
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_CLIENT_PORT: $XDEBUG_PORT
      PHP_XDEBUG_MODE: $XDEBUG_MODE
      PHP_XDEBUG_IDEKEY: $XDEBUG_IDE_KEY
      PHP_EXTENSIONS_DISABLE: $EXTENSIONS_DISABLE
    extra_hosts:
      - "store.itron.local:host-gateway"
    volumes:
      - ./:/srv/web
    networks:
      - store

  nginx:
    container_name: "${PROJECT_NAME}_nginx"
    image: nginx:alpine
    working_dir: /srv/web/
    depends_on:
      - php
    volumes:
      - ./:/srv/web/
      - ./dev-local/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dev-local/nginx/access.log:/var/log/nginx/store.itron.local.access.log
      - ./dev-local/nginx/ssl/:/etc/nginx/ssl/
      - ./dev-local/php-fpm/error.log:/var/log/php/store.itron.local.error.log
    ports:
      - "80:80"
      - "443:443"
    networks:
      - store

networks:
  store:
    driver: bridge
